# Generated by Django 3.0.5 on 2020-05-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('author', models.CharField(default='', max_length=512)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('publisher', models.TextField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=11)),
                ('city', models.CharField(max_length=128)),
                ('mail', models.EmailField(max_length=128)),
                ('password', models.CharField(default='', max_length=128)),
            ],
        ),
    ]
