# Generated by Django 3.0.5 on 2020-05-17 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200517_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='personid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Person'),
        ),
    ]
