# Generated by Django 3.0.5 on 2020-05-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200517_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='possibility',
            field=models.TextField(default='есть', max_length=64),
        ),
        migrations.AddField(
            model_name='book',
            name='wishes',
            field=models.CharField(default='', max_length=512),
        ),
    ]
