# Generated by Django 3.0.5 on 2020-05-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200529_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
